export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_USER_FROM_FS = 'GET_USER_FROM_FS';
export const GET_USER_FROM_FS_SUCCESS = 'GET_USER_FROM_FS_SUCCESS';

export const GET_POPULAR_PRODUCTS = 'GET_POPULAR_PRODUCTS';
export const GET_POPULAR_PRODUCTS_SUCCESS = 'GET_POPULAR_PRODUCTS_SUCCESS';

export const GET_WISHLIST_ITEMS = 'GET_WISHLIST_ITEMS';
export const GET_WISHLIST_ITEMS_SUCCESS = 'GET_WISHLIST_ITEMS_SUCCESS';
export const SET_WISHLIST_ITEMS = 'SET_WISHLIST_ITEM';
export const SET_WISHLIST_ITEMS_SUCCESS = 'SET_WISHLIST_ITEM_SUCCESS';
export const REMOVE_WISHLIST_ITEM = 'REMOVE_WISHLIST_ITEM';
export const REMOVE_WISHLIST_ITEM_SUCCESS = 'REMOVE_WISHLIST_ITEM_SUCCESS';

export const GET_ADD_TO_CART_ITEMS = 'GET_ADD_TO_CART_ITEMS';
export const GET_ADD_TO_CART_ITEMS_SUCCESS = 'GET_ADD_TO_CART_ITEMS_SUCCESS';
export const SET_ADD_TO_CART_ITEMS = 'SET_ADD_TO_CART_ITEMS';
export const SET_ADD_TO_CART_ITEMS_SUCCESS = 'SET_ADD_TO_CART_ITEMS_SUCCESS';
export const REMOVE_ADD_TO_CART_ITEM = 'REMOVE_ADD_TO_CART_ITEM';
export const REMOVE_ADD_TO_CART_ITEM_SUCCESS =
  'REMOVE_ADD_TO_CART_ITEM_SUCCESS';

export const GET_ADDRESS = 'GET_ADDRESS';
export const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_ADDRESS_SUCCESS = 'SET_ADDRESS_SUCCESS';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';
export const REMOVE_ADDRESS_SUCCESS = 'REMOVE_ADDRESS_SUCCESS';

export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const SET_ORDER = 'SET_ORDER';
export const SET_ORDER_SUCCESS = 'SET_ORDER_SUCCESS';
