const Images = {
  Logo: require('../../assets/images/cartImage.png'),
  userIcon: require('../../assets/images/userIcon.png'),
  userImage: require('../../assets/images/userImage.jpg'),
  addressImage: require('../../assets/images/addressImage.png'),
  allIconImage: require('../../assets/images/allImage.png'),
  bikeImage: require('../../assets/images/bikeImage.jpeg'),
  carImage: require('../../assets/images/carImage.png'),
  furnitureImage: require('../../assets/images/furnitureImage.png'),
  groceriesImage: require('../../assets/images/groceriesImage.png'),
  laptopImage: require('../../assets/images/laptopImage.png'),
  lightImage: require('../../assets/images/lightImage.png'),
  mensShirtImage: require('../../assets/images/mensShirtImage.png'),
  mensShoeImage: require('../../assets/images/mensShoeImage.png'),
  menWatchImage: require('../../assets/images/menWatchImage.png'),
  perfumeImage: require('../../assets/images/perfumeImage.png'),
  shirtImage: require('../../assets/images/shirtImage.png'),
  skinCareImage: require('../../assets/images/skinCareImage.png'),
  smartPhoneImage: require('../../assets/images/smartphoneImage.png'),
  sunGlassesImage: require('../../assets/images/sunGlassesImage.png'),
  topsImage: require('../../assets/images/topsImage.png'),
  womenBagImage: require('../../assets/images/womenBagImage.png'),
  womenDressImage: require('../../assets/images/womenDressImage.png'),
  womenJewelleryImage: require('../../assets/images/womenJewelleryImage.png'),
  womenShoeImage: require('../../assets/images/womensShoeImage.png'),
  womenWatchImage: require('../../assets/images/womenWatchImage.png'),
  creditCardImage: require('../../assets/images/creditCardImage.png'),
  americanExpressLogo: require('../../assets/images/americanExpressImage.png'),
  discoverLogo: require('../../assets/images/discoverImage.png'),
  mastercardLogo: require('../../assets/images/mastercardImage.jpeg'),
  paypalLogo: require('../../assets/images/paypalImage.png'),
  visaLogo: require('../../assets/images/visaImage.png'),
};

export default Images;
